version: "3.8"

services:
  my_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000" # 3001 is the port you reverse proxy (e.g. via Nginx), 3000 is the port exposed in the Dockerfile
    environment:
      NODE_ENV: production
      POSTGRES_HOST: my_db # The name of the donor-drop-backend's Docker service
      POSTGRES_PORT: 5432 # Use the internal (Docker) Postgres port
    networks:
      - your_shared_network # Use the same shared network id as the donor-drop-backend

networks:
  your_shared_network:
    external: true
